% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\author{}
\date{\vspace{-2.5em}}

\begin{document}

\hypertarget{actsc-632-assignment-solutions}{%
\section{ActSc 632 Assignment
Solutions}\label{actsc-632-assignment-solutions}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Install the packages if necessary}
\CommentTok{\# install.packages("insuranceData")}
\CommentTok{\# install.packages("doParallel")}
\CommentTok{\# install.packages("dplyr")}
\CommentTok{\# install.packages("tibble")}

\FunctionTok{library}\NormalTok{(insuranceData)}
\FunctionTok{library}\NormalTok{(foreach)}
\FunctionTok{library}\NormalTok{(dplyr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'dplyr'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     filter, lag
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tibble)}

\FunctionTok{options}\NormalTok{(}\AttributeTok{tibble.print\_max =} \ConstantTok{Inf}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{question-1}{%
\subsection{Question 1}\label{question-1}}

Download the data set dataOhlsson and briefly discuss the data found in
there (e.g., how many rating factors, what are the levels for each, how
is the exposure determined, etc.). If there are any problems with the
data, explain how you dealt with them.

\hypertarget{solution}{%
\paragraph{Solution:}\label{solution}}

As stated in the R documentation for this dataset:

\begin{quote}
The data for this case study comes from the former Swedish insurance
company Wasa, and concerns partial casco insurance, for motorcycles this
time. It contains aggregated data on all insurance policies and claims
during 1994-1998; the reason for using this rather old data set is
confidentiality; more recent data for ongoing business can not be
disclosed.
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Load the data}
\FunctionTok{data}\NormalTok{(dataOhlsson)}

\CommentTok{\# change categorical columns into factors}
\NormalTok{dataOhlsson }\OtherTok{\textless{}{-}} \FunctionTok{within}\NormalTok{(dataOhlsson, \{}
\NormalTok{    zon }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(zon)}
\NormalTok{    mcklass }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(mcklass)}
\NormalTok{    bonuskl }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(bonuskl)}
\NormalTok{    kon }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(kon)\})}

\CommentTok{\# regroup the column bonuskl into 3 levels}
\FunctionTok{levels}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{bonuskl) }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{(}\StringTok{"1"} \OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"1"}\NormalTok{,}\StringTok{"2"}\NormalTok{),}
                                    \StringTok{"2"} \OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"3"}\NormalTok{,}\StringTok{"4"}\NormalTok{),}
                                    \StringTok{"3"} \OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"5"}\NormalTok{,}\StringTok{"6"}\NormalTok{,}\StringTok{"7"}\NormalTok{))  }

\CommentTok{\# regroup the column mcklass into 3 levels}
\CommentTok{\# For details, visit: https://stackoverflow.com/questions/13559076/group{-}numeric{-}values{-}by{-}the{-}intervals}
\NormalTok{dataOhlsson}\SpecialCharTok{$}\NormalTok{motorage\_gr }\OtherTok{\textless{}{-}} \FunctionTok{cut}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{fordald, }
                               \AttributeTok{breaks =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{5}\NormalTok{, }\DecValTok{100}\NormalTok{), }
                               \AttributeTok{labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"1"}\NormalTok{, }\StringTok{"2"}\NormalTok{, }\StringTok{"3"}\NormalTok{), }
                               \AttributeTok{right =} \ConstantTok{FALSE}\NormalTok{)}

\FunctionTok{summary}\NormalTok{(dataOhlsson)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     agarald      kon       zon       mcklass      fordald      bonuskl  
##  Min.   : 0.00   K: 9853   1: 8582   1: 7032   Min.   : 0.00   1:23424  
##  1st Qu.:31.00   M:54695   2:11794   2: 5204   1st Qu.: 5.00   2:12721  
##  Median :44.00             3:12722   3:18905   Median :12.00   3:28403  
##  Mean   :42.42             4:24816   4:12378   Mean   :12.54            
##  3rd Qu.:52.00             5: 2377   5:11816   3rd Qu.:16.00            
##  Max.   :92.00             6: 3884   6: 8407   Max.   :99.00            
##                            7:  373   7:  806                            
##     duration          antskad          skadkost      motorage_gr
##  Min.   : 0.0000   Min.   :0.0000   Min.   :     0   1: 5104    
##  1st Qu.: 0.4630   1st Qu.:0.0000   1st Qu.:     0   2: 8989    
##  Median : 0.8274   Median :0.0000   Median :     0   3:50455    
##  Mean   : 1.0107   Mean   :0.0108   Mean   :   264              
##  3rd Qu.: 1.0000   3rd Qu.:0.0000   3rd Qu.:     0              
##  Max.   :31.3397   Max.   :2.0000   Max.   :365347              
## 
\end{verbatim}

In this data set we have 6 rating factors given by agarald (age of
driver),which goes from 0 to 99, kon (sex of driver), either M (male) or
K (female), zon (geographical zone, going from 1 to 7, generally going
from more to less urban), mcklass (class of the vehicle, with 7 possible
classes, as determined by the EV ratio of engine power to vehicle
weight), fordald (age of vehicle, a numerical value between 0 and 99),
bonuskl (bonus class based on experience, going from 1 to 7: a new
driver starts with bonus class 1; for each claim-free year the bonus
class is increased by 1; after the first claim the bonus is decreased by
2; the driver can not return to class 7 with less than 6 consecutive
claim free years). There are 64548 observations in this data set, with
one for each driver observed. We see that for some observations the
duration is 0. The exposure (or duration) is determined using
policy-years, i.e., how long the contract was in effect for each driver.
For each observation we also have the number of claims (antskad) and the
claim cost (skadkost).

\hypertarget{question-2}{%
\subsection{Question 2}\label{question-2}}

Use only the rating factors contained in the current tariff. Compute the
exposure (in policy years), the claim frequency and the average claim
severity for each rating factor (i.e., for each possible value of each
rating factor).

\hypertarget{solution-1}{%
\paragraph{Solution:}\label{solution-1}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{motorcycle }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{rating.factor =} \FunctionTok{c}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\StringTok{"Zone"}\NormalTok{, }\FunctionTok{nlevels}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{zon)),}
                                           \FunctionTok{rep}\NormalTok{(}\StringTok{"Vehicle class"}\NormalTok{, }\FunctionTok{nlevels}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{mcklass)),}
                                           \FunctionTok{rep}\NormalTok{(}\StringTok{"Vehicle age"}\NormalTok{, }\FunctionTok{nlevels}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{motorage\_gr)),}
                                           \FunctionTok{rep}\NormalTok{(}\StringTok{"Bonus class"}\NormalTok{, }\FunctionTok{nlevels}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{bonuskl))),}
                         \AttributeTok{class =} \FunctionTok{c}\NormalTok{(}\FunctionTok{levels}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{zon),}
                                   \FunctionTok{levels}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{mcklass),}
                                   \FunctionTok{levels}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{motorage\_gr),}
                                   \FunctionTok{levels}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{bonuskl)),}
                         \AttributeTok{stringsAsFactors =} \ConstantTok{FALSE}\NormalTok{)}

\NormalTok{new.cols }\OtherTok{\textless{}{-}} \FunctionTok{foreach}\NormalTok{ (}\AttributeTok{rating.factor =} \FunctionTok{c}\NormalTok{(}\StringTok{"zon"}\NormalTok{,}\StringTok{"mcklass"}\NormalTok{,}\StringTok{"motorage\_gr"}\NormalTok{,}\StringTok{"bonuskl"}\NormalTok{), }\AttributeTok{.combine =}\NormalTok{ rbind) }\SpecialCharTok{\%do\%}\NormalTok{ \{}
\NormalTok{                nclaims }\OtherTok{\textless{}{-}} \FunctionTok{tapply}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{antskad,dataOhlsson[[rating.factor]], sum)}
\NormalTok{                sums }\OtherTok{\textless{}{-}} \FunctionTok{tapply}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{duration, dataOhlsson[[rating.factor]],sum)}
\NormalTok{                severity }\OtherTok{\textless{}{-}} \FunctionTok{tapply}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{skadkost,dataOhlsson[[rating.factor]],sum)}
\NormalTok{                n.levels }\OtherTok{\textless{}{-}} \FunctionTok{nlevels}\NormalTok{(dataOhlsson[[rating.factor]])}
                \FunctionTok{contrasts}\NormalTok{(dataOhlsson[[rating.factor]]) }\OtherTok{\textless{}{-}}
                    \FunctionTok{contr.treatment}\NormalTok{(n.levels)[}\FunctionTok{rank}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{sums, }\AttributeTok{ties.method =} \StringTok{"first"}\NormalTok{), ]}
                \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{duration =}\NormalTok{ sums, }\AttributeTok{n.claims =}\NormalTok{ nclaims, }\AttributeTok{totcostperm =}\NormalTok{ severity}\SpecialCharTok{/}\DecValTok{1000}\NormalTok{)\}}

\NormalTok{motorcycle }\OtherTok{\textless{}{-}} \FunctionTok{cbind}\NormalTok{(motorcycle, new.cols)}
\FunctionTok{rm}\NormalTok{(new.cols)}
\end{Highlighting}
\end{Shaded}

After grouping the classes for the vehicle age into 3 groups (0-2, 3-5,
6 and up) and the bonus class into three groups (1-2,3-4,5-7) we get

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{motorcycle}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    rating.factor class   duration n.claims totcostperm
## 1           Zone     1  6205.3096      183    5539.963
## 2           Zone     2 10103.0904      167    4811.166
## 3           Zone     3 11676.5726      123    2522.628
## 4           Zone     4 32628.4931      196    3774.629
## 5           Zone     5  1582.1123        9     104.739
## 6           Zone     6  2799.9452       18     288.045
## 7           Zone     7   241.2877        1       0.650
## 11 Vehicle class     1  5190.3507       46     993.062
## 21 Vehicle class     2  3990.1151       57     883.137
## 31 Vehicle class     3 21665.6794      166    5371.543
## 41 Vehicle class     4 11739.8821       98    2191.578
## 51 Vehicle class     5 13439.9260      149    3297.119
## 61 Vehicle class     6  8880.1342      175    4160.776
## 71 Vehicle class     7   330.7233        6     144.605
## 12   Vehicle age     1  4955.4027      126    4964.419
## 22   Vehicle age     2  9753.8109      145    5506.945
## 32   Vehicle age     3 50527.5972      426    6570.456
## 13   Bonus class     1 19893.3698      207    4558.072
## 23   Bonus class     2  9615.7644      121    3627.142
## 33   Bonus class     3 35727.6766      369    8856.606
\end{verbatim}

\hypertarget{question-3}{%
\subsection{Question 3}\label{question-3}}

Use a relative Poisson glm to determine relativities for the claim
frequency, using the current rating factors. Provide a 95\% confidence
interval for each relativity. Comment on the overall fit of this model
to the data.

\hypertarget{solution-2}{%
\paragraph{Solution:}\label{solution-2}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Group the data by rating factors}
\NormalTok{grDataOhlsson }\OtherTok{\textless{}{-}}\NormalTok{ dataOhlsson }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{group\_by}\NormalTok{(bonuskl, zon, mcklass, motorage\_gr) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{summarize}\NormalTok{(}\AttributeTok{duration =} \FunctionTok{sum}\NormalTok{(duration), }
                                                                                            \AttributeTok{antskad=}\FunctionTok{sum}\NormalTok{(antskad),}
                                                                                            \AttributeTok{skadkost=}\FunctionTok{sum}\NormalTok{(skadkost))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'bonuskl', 'zon', 'mcklass'. You can
## override using the `.groups` argument.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Fit the Poisson GLM}
\NormalTok{model.freq }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(antskad }\SpecialCharTok{\textasciitilde{}}\NormalTok{ zon }\SpecialCharTok{+}\NormalTok{ mcklass }\SpecialCharTok{+}\NormalTok{ motorage\_gr }\SpecialCharTok{+}\NormalTok{ bonuskl }\SpecialCharTok{+} \FunctionTok{offset}\NormalTok{(}\FunctionTok{log}\NormalTok{(duration)), }
                  \AttributeTok{family =}\NormalTok{ poisson, }
                  \AttributeTok{data =}\NormalTok{ grDataOhlsson[grDataOhlsson}\SpecialCharTok{$}\NormalTok{duration}\SpecialCharTok{\textgreater{}}\DecValTok{0}\NormalTok{,])}

\CommentTok{\# Examine model fit}
\FunctionTok{with}\NormalTok{(model.freq, }\FunctionTok{cbind}\NormalTok{(}\AttributeTok{res.deviance =}\NormalTok{ deviance, }
                       \AttributeTok{df =}\NormalTok{ df.residual, }
                       \AttributeTok{p =} \FunctionTok{pchisq}\NormalTok{(deviance, df.residual, }\AttributeTok{lower.tail =} \ConstantTok{FALSE}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      res.deviance  df        p
## [1,]     360.2168 389 0.849545
\end{verbatim}

With a deviance of \(360.2168\) on \(389\) degrees of freedom, the model
seems a reasonable fit (p-value of \(0.8495\)).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Generate the table for relative frequency}
\NormalTok{P.zon }\OtherTok{=} \FunctionTok{contrasts}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{zon)}
\NormalTok{P.mcklass }\OtherTok{=} \FunctionTok{contrasts}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{mcklass)}
\NormalTok{P.motorage\_gr }\OtherTok{=} \FunctionTok{contrasts}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{motorage\_gr)}
\NormalTok{P.bonuskl }\OtherTok{=} \FunctionTok{contrasts}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{bonuskl)}

\NormalTok{mat.freq }\OtherTok{=} \FunctionTok{summary}\NormalTok{(model.freq)}\SpecialCharTok{$}\NormalTok{coefficients[, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{2}\NormalTok{]}

\NormalTok{table.q3 }\OtherTok{=} \FunctionTok{matrix}\NormalTok{(}\DecValTok{0}\NormalTok{, }\AttributeTok{nrow =} \FunctionTok{dim}\NormalTok{(motorcycle)[}\DecValTok{1}\NormalTok{] }\SpecialCharTok{+} \DecValTok{1}\NormalTok{, }\AttributeTok{ncol =} \DecValTok{5}\NormalTok{)}
\FunctionTok{colnames}\NormalTok{(table.q3) }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"Rating factor"}\NormalTok{, }\StringTok{"Class"}\NormalTok{, }\StringTok{"Multiplier"}\NormalTok{, }\StringTok{"Lower bound"}\NormalTok{, }\StringTok{"Upper bound"}\NormalTok{)}

\CommentTok{\# Intercept}
\NormalTok{estimate }\OtherTok{=}\NormalTok{ mat.freq[}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{]}
\NormalTok{std.error }\OtherTok{=}\NormalTok{ mat.freq[}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{]}
\NormalTok{table.q3[}\DecValTok{1}\NormalTok{, ] }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"Intercept"}\NormalTok{, }\StringTok{"0"}\NormalTok{, }\FunctionTok{exp}\NormalTok{(estimate), }\FunctionTok{exp}\NormalTok{(estimate }\SpecialCharTok{{-}} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ std.error), }\FunctionTok{exp}\NormalTok{(estimate }\SpecialCharTok{+} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ std.error))}

\CommentTok{\# Zone}
\NormalTok{estimate }\OtherTok{=}\NormalTok{ P.zon }\SpecialCharTok{\%*\%}\NormalTok{ mat.freq[}\DecValTok{2}\SpecialCharTok{:}\DecValTok{7}\NormalTok{, }\DecValTok{1}\NormalTok{]}
\NormalTok{std.error }\OtherTok{=}\NormalTok{ P.zon }\SpecialCharTok{\%*\%}\NormalTok{ mat.freq[}\DecValTok{2}\SpecialCharTok{:}\DecValTok{7}\NormalTok{, }\DecValTok{2}\NormalTok{]}
\NormalTok{table.q3[}\DecValTok{2}\SpecialCharTok{:}\DecValTok{8}\NormalTok{, ] }\OtherTok{=} \FunctionTok{cbind}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\StringTok{"Zone"}\NormalTok{, }\DecValTok{7}\NormalTok{), }\FunctionTok{seq}\NormalTok{(}\DecValTok{7}\NormalTok{), }\FunctionTok{exp}\NormalTok{(estimate), }\FunctionTok{exp}\NormalTok{(estimate }\SpecialCharTok{{-}} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ std.error), }\FunctionTok{exp}\NormalTok{(estimate }\SpecialCharTok{+} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ std.error))}

\CommentTok{\# Vehicle class}
\NormalTok{estimate }\OtherTok{=}\NormalTok{ P.mcklass }\SpecialCharTok{\%*\%}\NormalTok{ mat.freq[}\DecValTok{8}\SpecialCharTok{:}\DecValTok{13}\NormalTok{, }\DecValTok{1}\NormalTok{]}
\NormalTok{std.error }\OtherTok{=}\NormalTok{ P.mcklass }\SpecialCharTok{\%*\%}\NormalTok{ mat.freq[}\DecValTok{8}\SpecialCharTok{:}\DecValTok{13}\NormalTok{, }\DecValTok{2}\NormalTok{]}
\NormalTok{table.q3[}\DecValTok{9}\SpecialCharTok{:}\DecValTok{15}\NormalTok{, ] }\OtherTok{=} \FunctionTok{cbind}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\StringTok{"Vehicle class"}\NormalTok{, }\DecValTok{7}\NormalTok{), }\FunctionTok{seq}\NormalTok{(}\DecValTok{7}\NormalTok{), }\FunctionTok{exp}\NormalTok{(estimate), }\FunctionTok{exp}\NormalTok{(estimate }\SpecialCharTok{{-}} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ std.error), }\FunctionTok{exp}\NormalTok{(estimate }\SpecialCharTok{+} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ std.error))}

\CommentTok{\# Vehicle age}
\NormalTok{estimate }\OtherTok{=}\NormalTok{ P.motorage\_gr }\SpecialCharTok{\%*\%}\NormalTok{ mat.freq[}\DecValTok{14}\SpecialCharTok{:}\DecValTok{15}\NormalTok{, }\DecValTok{1}\NormalTok{]}
\NormalTok{std.error }\OtherTok{=}\NormalTok{ P.motorage\_gr }\SpecialCharTok{\%*\%}\NormalTok{ mat.freq[}\DecValTok{14}\SpecialCharTok{:}\DecValTok{15}\NormalTok{, }\DecValTok{2}\NormalTok{]}
\NormalTok{table.q3[}\DecValTok{16}\SpecialCharTok{:}\DecValTok{18}\NormalTok{, ] }\OtherTok{=} \FunctionTok{cbind}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\StringTok{"Vehicle age"}\NormalTok{, }\DecValTok{3}\NormalTok{), }\FunctionTok{seq}\NormalTok{(}\DecValTok{3}\NormalTok{), }\FunctionTok{exp}\NormalTok{(estimate), }\FunctionTok{exp}\NormalTok{(estimate }\SpecialCharTok{{-}} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ std.error), }\FunctionTok{exp}\NormalTok{(estimate }\SpecialCharTok{+} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ std.error))}

\CommentTok{\# Bonus class}
\NormalTok{estimate }\OtherTok{=}\NormalTok{ P.motorage\_gr }\SpecialCharTok{\%*\%}\NormalTok{ mat.freq[}\DecValTok{16}\SpecialCharTok{:}\DecValTok{17}\NormalTok{, }\DecValTok{1}\NormalTok{]}
\NormalTok{std.error }\OtherTok{=}\NormalTok{ P.motorage\_gr }\SpecialCharTok{\%*\%}\NormalTok{ mat.freq[}\DecValTok{16}\SpecialCharTok{:}\DecValTok{17}\NormalTok{, }\DecValTok{2}\NormalTok{]}
\NormalTok{table.q3[}\DecValTok{19}\SpecialCharTok{:}\DecValTok{21}\NormalTok{, ] }\OtherTok{=} \FunctionTok{cbind}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\StringTok{"Bonus class"}\NormalTok{, }\DecValTok{3}\NormalTok{), }\FunctionTok{seq}\NormalTok{(}\DecValTok{3}\NormalTok{), }\FunctionTok{exp}\NormalTok{(estimate), }\FunctionTok{exp}\NormalTok{(estimate }\SpecialCharTok{{-}} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ std.error), }\FunctionTok{exp}\NormalTok{(estimate }\SpecialCharTok{+} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ std.error))}

\FunctionTok{as\_tibble}\NormalTok{(table.q3)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 21 x 5
##    `Rating factor` Class Multiplier          `Lower bound`       `Upper bound`  
##    <chr>           <chr> <chr>               <chr>               <chr>          
##  1 Intercept       0     0.00234497033954873 0.00185823280920728 0.002959201810~
##  2 Zone            1     5.15619166509121    4.20563293521715    6.321596034815 
##  3 Zone            2     2.72512290204893    2.21581010710497    3.351503275239~
##  4 Zone            3     1.70851751432824    1.36352962622445    2.1407911061302
##  5 Zone            4     1                   1                   1              
##  6 Zone            5     0.906778337752537   0.464785438953093   1.769089314995~
##  7 Zone            6     1.03510019180549    0.638608104454922   1.677761994565~
##  8 Zone            7     0.727879994146364   0.102010643107309   5.193666756136~
##  9 Vehicle class   1     1.47808347047319    1.06238984535683    2.056430372743~
## 10 Vehicle class   2     2.1033504745518     1.5548677882858     2.845311512739~
## 11 Vehicle class   3     1                   1                   1              
## 12 Vehicle class   4     1.32127812054859    1.02781661273447    1.698528560650~
## 13 Vehicle class   5     2.04515054171011    1.63104519770581    2.564392908388~
## 14 Vehicle class   6     3.97983541065762    3.18692242660292    4.970026808216~
## 15 Vehicle class   7     3.31183418327132    1.46441692364757    7.489838092122~
## 16 Vehicle age     1     3.23993950825312    2.64393379410273    3.970299120406~
## 17 Vehicle age     2     1.89477011838352    1.56371868235732    2.295907724340~
## 18 Vehicle age     3     1                   1                   1              
## 19 Bonus class     1     1.44301072819081    1.17184971216712    1.776917244637~
## 20 Bonus class     2     1.27596653236492    1.06785602203578    1.524634930289~
## 21 Bonus class     3     1                   1                   1
\end{verbatim}

Note that I also accepted answers based on the quasi-Poisson family
where a dispersion parameter is estimated, causing the CIs to be
different from the above.

\hypertarget{question-4}{%
\subsection{Question 4}\label{question-4}}

Use a Gamma glm (with log link function) to determine relativities for
the severity, still using the current rating factors. Provide a 95\%
confidence interval for each relativity. Comment on the overall fit of
this model to the data.

\hypertarget{solution-3}{%
\paragraph{Solution:}\label{solution-3}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model.sev }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(skadkost}\SpecialCharTok{/}\NormalTok{antskad }\SpecialCharTok{\textasciitilde{}}\NormalTok{ zon }\SpecialCharTok{+}\NormalTok{ mcklass }\SpecialCharTok{+}\NormalTok{ motorage\_gr }\SpecialCharTok{+}\NormalTok{ bonuskl, }
                 \AttributeTok{family=}\FunctionTok{Gamma}\NormalTok{(}\StringTok{"log"}\NormalTok{), }
                 \AttributeTok{data=}\NormalTok{grDataOhlsson[grDataOhlsson}\SpecialCharTok{$}\NormalTok{skadkost}\SpecialCharTok{\textgreater{}}\DecValTok{0}\NormalTok{,],}
                 \AttributeTok{weights=}\NormalTok{antskad)}

\FunctionTok{with}\NormalTok{(model.sev, }\FunctionTok{cbind}\NormalTok{(}\AttributeTok{res.deviance =}\NormalTok{ deviance, }
                      \AttributeTok{df =}\NormalTok{ df.residual, }
                      \AttributeTok{p =} \FunctionTok{pchisq}\NormalTok{(deviance, df.residual, }\AttributeTok{lower.tail =} \ConstantTok{FALSE}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      res.deviance  df           p
## [1,]     351.1129 164 1.13842e-15
\end{verbatim}

The severity model doesn't seem to be a very good fit. We reject the
hypothesis that the data comes from this model based on the residual
deviance, given by \(351\) on \(164\) degrees of freedom, as its
corresponding p-value is \(1.13842 \times 10^{-15}\).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Generate the table for relative severity}
\NormalTok{mat.sev }\OtherTok{=} \FunctionTok{summary}\NormalTok{(model.sev)}\SpecialCharTok{$}\NormalTok{coefficients[, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{2}\NormalTok{]}

\NormalTok{table.q4 }\OtherTok{=} \FunctionTok{matrix}\NormalTok{(}\DecValTok{0}\NormalTok{, }\AttributeTok{nrow =} \FunctionTok{dim}\NormalTok{(motorcycle)[}\DecValTok{1}\NormalTok{] }\SpecialCharTok{+} \DecValTok{1}\NormalTok{, }\AttributeTok{ncol =} \DecValTok{5}\NormalTok{)}
\FunctionTok{colnames}\NormalTok{(table.q4) }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"Rating factor"}\NormalTok{, }\StringTok{"Class"}\NormalTok{, }\StringTok{"Multiplier"}\NormalTok{, }\StringTok{"Lower bound"}\NormalTok{, }\StringTok{"Upper bound"}\NormalTok{)}

\CommentTok{\# Intercept}
\NormalTok{estimate }\OtherTok{=}\NormalTok{ mat.sev[}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{]}
\NormalTok{std.error }\OtherTok{=}\NormalTok{ mat.sev[}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{]}
\NormalTok{table.q4[}\DecValTok{1}\NormalTok{, ] }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"Intercept"}\NormalTok{, }\StringTok{"0"}\NormalTok{, }\FunctionTok{exp}\NormalTok{(estimate), }\FunctionTok{exp}\NormalTok{(estimate }\SpecialCharTok{{-}} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ std.error), }\FunctionTok{exp}\NormalTok{(estimate }\SpecialCharTok{+} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ std.error))}

\CommentTok{\# Zone}
\NormalTok{estimate }\OtherTok{=}\NormalTok{ P.zon }\SpecialCharTok{\%*\%}\NormalTok{ mat.sev[}\DecValTok{2}\SpecialCharTok{:}\DecValTok{7}\NormalTok{, }\DecValTok{1}\NormalTok{]}
\NormalTok{std.error }\OtherTok{=}\NormalTok{ P.zon }\SpecialCharTok{\%*\%}\NormalTok{ mat.sev[}\DecValTok{2}\SpecialCharTok{:}\DecValTok{7}\NormalTok{, }\DecValTok{2}\NormalTok{]}
\NormalTok{table.q4[}\DecValTok{2}\SpecialCharTok{:}\DecValTok{8}\NormalTok{, ] }\OtherTok{=} \FunctionTok{cbind}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\StringTok{"Zone"}\NormalTok{, }\DecValTok{7}\NormalTok{), }\FunctionTok{seq}\NormalTok{(}\DecValTok{7}\NormalTok{), }\FunctionTok{exp}\NormalTok{(estimate), }\FunctionTok{exp}\NormalTok{(estimate }\SpecialCharTok{{-}} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ std.error), }\FunctionTok{exp}\NormalTok{(estimate }\SpecialCharTok{+} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ std.error))}

\CommentTok{\# Vehicle class}
\NormalTok{estimate }\OtherTok{=}\NormalTok{ P.mcklass }\SpecialCharTok{\%*\%}\NormalTok{ mat.sev[}\DecValTok{8}\SpecialCharTok{:}\DecValTok{13}\NormalTok{, }\DecValTok{1}\NormalTok{]}
\NormalTok{std.error }\OtherTok{=}\NormalTok{ P.mcklass }\SpecialCharTok{\%*\%}\NormalTok{ mat.sev[}\DecValTok{8}\SpecialCharTok{:}\DecValTok{13}\NormalTok{, }\DecValTok{2}\NormalTok{]}
\NormalTok{table.q4[}\DecValTok{9}\SpecialCharTok{:}\DecValTok{15}\NormalTok{, ] }\OtherTok{=} \FunctionTok{cbind}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\StringTok{"Vehicle class"}\NormalTok{, }\DecValTok{7}\NormalTok{), }\FunctionTok{seq}\NormalTok{(}\DecValTok{7}\NormalTok{), }\FunctionTok{exp}\NormalTok{(estimate), }\FunctionTok{exp}\NormalTok{(estimate }\SpecialCharTok{{-}} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ std.error), }\FunctionTok{exp}\NormalTok{(estimate }\SpecialCharTok{+} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ std.error))}

\CommentTok{\# Vehicle age}
\NormalTok{estimate }\OtherTok{=}\NormalTok{ P.motorage\_gr }\SpecialCharTok{\%*\%}\NormalTok{ mat.sev[}\DecValTok{14}\SpecialCharTok{:}\DecValTok{15}\NormalTok{, }\DecValTok{1}\NormalTok{]}
\NormalTok{std.error }\OtherTok{=}\NormalTok{ P.motorage\_gr }\SpecialCharTok{\%*\%}\NormalTok{ mat.sev[}\DecValTok{14}\SpecialCharTok{:}\DecValTok{15}\NormalTok{, }\DecValTok{2}\NormalTok{]}
\NormalTok{table.q4[}\DecValTok{16}\SpecialCharTok{:}\DecValTok{18}\NormalTok{, ] }\OtherTok{=} \FunctionTok{cbind}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\StringTok{"Vehicle age"}\NormalTok{, }\DecValTok{3}\NormalTok{), }\FunctionTok{seq}\NormalTok{(}\DecValTok{3}\NormalTok{), }\FunctionTok{exp}\NormalTok{(estimate), }\FunctionTok{exp}\NormalTok{(estimate }\SpecialCharTok{{-}} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ std.error), }\FunctionTok{exp}\NormalTok{(estimate }\SpecialCharTok{+} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ std.error))}

\CommentTok{\# Bonus class}
\NormalTok{estimate }\OtherTok{=}\NormalTok{ P.motorage\_gr }\SpecialCharTok{\%*\%}\NormalTok{ mat.sev[}\DecValTok{16}\SpecialCharTok{:}\DecValTok{17}\NormalTok{, }\DecValTok{1}\NormalTok{]}
\NormalTok{std.error }\OtherTok{=}\NormalTok{ P.motorage\_gr }\SpecialCharTok{\%*\%}\NormalTok{ mat.sev[}\DecValTok{16}\SpecialCharTok{:}\DecValTok{17}\NormalTok{, }\DecValTok{2}\NormalTok{]}
\NormalTok{table.q4[}\DecValTok{19}\SpecialCharTok{:}\DecValTok{21}\NormalTok{, ] }\OtherTok{=} \FunctionTok{cbind}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\StringTok{"Bonus class"}\NormalTok{, }\DecValTok{3}\NormalTok{), }\FunctionTok{seq}\NormalTok{(}\DecValTok{3}\NormalTok{), }\FunctionTok{exp}\NormalTok{(estimate), }\FunctionTok{exp}\NormalTok{(estimate }\SpecialCharTok{{-}} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ std.error), }\FunctionTok{exp}\NormalTok{(estimate }\SpecialCharTok{+} \FloatTok{1.96} \SpecialCharTok{*}\NormalTok{ std.error))}

\FunctionTok{as\_tibble}\NormalTok{(table.q4)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 21 x 5
##    `Rating factor` Class Multiplier         `Lower bound`       `Upper bound`   
##    <chr>           <chr> <chr>              <chr>               <chr>           
##  1 Intercept       0     15698.1679330244   11322.3990123379    21765.0407996487
##  2 Zone            1     1.30039469226393   0.967902679007292   1.74710370406512
##  3 Zone            2     1.36973027703226   1.0186593887144     1.84179427648203
##  4 Zone            3     0.936380318134884  0.677075531329196   1.2949930393572 
##  5 Zone            4     1                  1                   1               
##  6 Zone            5     0.96339135135138   0.36576430540324    2.53748898443062
##  7 Zone            6     0.78451446232571   0.387815300888558   1.58700015236133
##  8 Zone            7     0.0176535454001371 0.00104756310507183 0.2974977485230~
##  9 Vehicle class   1     0.745942949078776  0.466065835461491   1.19388901941155
## 10 Vehicle class   2     0.667289538253253  0.430200054122025   1.0350424729048 
## 11 Vehicle class   3     1                  1                   1               
## 12 Vehicle class   4     0.797635610340983  0.555995256341655   1.14429495508695
## 13 Vehicle class   5     0.833034093463106  0.601004157341868   1.15464392782422
## 14 Vehicle class   6     1.03466202092935   0.750353624581498   1.42669464434278
## 15 Vehicle class   7     1.4329900900771    0.435415448857646   4.71609494712838
## 16 Vehicle age     1     2.55576215878475   1.91010115168082    3.41967241186585
## 17 Vehicle age     2     2.3454838512553    1.77392394528234    3.10120087793493
## 18 Vehicle age     3     1                  1                   1               
## 19 Bonus class     1     1.03083084936552   0.766438737547944   1.38642814871705
## 20 Bonus class     2     0.835563065106195  0.645526021612162   1.08154530165342
## 21 Bonus class     3     1                  1                   1
\end{verbatim}

\hypertarget{question-5}{%
\subsection{Question 5}\label{question-5}}

Assess whether rating factors for the policyholder's age and sex would
have a significant impact. Include an interaction term. (I leave it up
to you to decide how to handle the age variable, e.g., group it into
intervals etc.).

\hypertarget{solution-4}{%
\paragraph{Solution:}\label{solution-4}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dataOhlsson}\SpecialCharTok{$}\NormalTok{driverage\_gr }\OtherTok{\textless{}{-}} \FunctionTok{cut}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{agarald, }
                                \AttributeTok{breaks =} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{30}\NormalTok{,}\DecValTok{100}\NormalTok{), }
                                \AttributeTok{labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"1"}\NormalTok{, }\StringTok{"2"}\NormalTok{), }
                                \AttributeTok{right =} \ConstantTok{FALSE}\NormalTok{)}

\NormalTok{motorcycle.new }\OtherTok{\textless{}{-}}
    \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{rating.factor =} \FunctionTok{c}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\StringTok{"Bonus class"}\NormalTok{, }\FunctionTok{nlevels}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{bonuskl)),}
                                 \FunctionTok{rep}\NormalTok{(}\StringTok{"Vehicle class"}\NormalTok{, }\FunctionTok{nlevels}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{mcklass)),}
                                 \FunctionTok{rep}\NormalTok{(}\StringTok{"Vehicle age"}\NormalTok{, }\FunctionTok{nlevels}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{motorage\_gr)),}
                                 \FunctionTok{rep}\NormalTok{(}\StringTok{"Zone"}\NormalTok{, }\FunctionTok{nlevels}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{zon)),}
                                 \FunctionTok{rep}\NormalTok{(}\StringTok{"Driver age"}\NormalTok{, }\FunctionTok{nlevels}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{driverage\_gr)),}
                                 \FunctionTok{rep}\NormalTok{(}\StringTok{"Sex"}\NormalTok{, }\FunctionTok{nlevels}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{kon))),}
               \AttributeTok{class =} \FunctionTok{c}\NormalTok{(}\FunctionTok{levels}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{bonuskl),}
                         \FunctionTok{levels}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{mcklass),}
                         \FunctionTok{levels}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{motorage\_gr),}
                         \FunctionTok{levels}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{zon),}
                         \FunctionTok{levels}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{driverage\_gr),}
                         \FunctionTok{levels}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{kon)),}
               \AttributeTok{stringsAsFactors =} \ConstantTok{FALSE}\NormalTok{)}

\NormalTok{new.cols }\OtherTok{\textless{}{-}} \FunctionTok{foreach}\NormalTok{ (}\AttributeTok{rating.factor =} \FunctionTok{c}\NormalTok{(}\StringTok{"zon"}\NormalTok{, }\StringTok{"mcklass"}\NormalTok{, }\StringTok{"motorage\_gr"}\NormalTok{, }\StringTok{"bonuskl"}\NormalTok{, }\StringTok{"driverage\_gr"}\NormalTok{, }\StringTok{"kon"}\NormalTok{), }\AttributeTok{.combine =}\NormalTok{ rbind) }\SpecialCharTok{\%do\%}\NormalTok{ \{}
\NormalTok{    nclaims }\OtherTok{\textless{}{-}} \FunctionTok{tapply}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{antskad,dataOhlsson[[rating.factor]], sum)}
\NormalTok{    sums }\OtherTok{\textless{}{-}} \FunctionTok{tapply}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{duration, dataOhlsson[[rating.factor]],sum)}
\NormalTok{    severity }\OtherTok{\textless{}{-}} \FunctionTok{tapply}\NormalTok{(dataOhlsson}\SpecialCharTok{$}\NormalTok{skadkost,dataOhlsson[[rating.factor]],sum)}
\NormalTok{    n.levels }\OtherTok{\textless{}{-}} \FunctionTok{nlevels}\NormalTok{(dataOhlsson[[rating.factor]])}
    \FunctionTok{contrasts}\NormalTok{(dataOhlsson[[rating.factor]]) }\OtherTok{\textless{}{-}}
        \FunctionTok{contr.treatment}\NormalTok{(n.levels)[}\FunctionTok{rank}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{sums, }\AttributeTok{ties.method =} \StringTok{"first"}\NormalTok{), ]}
    \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{duration =}\NormalTok{ sums, }\AttributeTok{n.claims =}\NormalTok{ nclaims, }\AttributeTok{sev =}\NormalTok{ severity}\SpecialCharTok{/}\NormalTok{nclaims)\}}

\NormalTok{motorcycle.new }\OtherTok{\textless{}{-}} \FunctionTok{cbind}\NormalTok{(motorcycle.new, new.cols)}
\FunctionTok{rm}\NormalTok{(new.cols)}

\NormalTok{grDataOhlsson.new }\OtherTok{\textless{}{-}}\NormalTok{ dataOhlsson }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{group\_by}\NormalTok{(bonuskl, zon, mcklass, motorage\_gr, kon, driverage\_gr) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{summarize}\NormalTok{(}\AttributeTok{duration =} \FunctionTok{sum}\NormalTok{(duration),}
                                                                                                                   \AttributeTok{antskad=}\FunctionTok{sum}\NormalTok{(antskad),}
                                                                                                                   \AttributeTok{skadkost=}\FunctionTok{sum}\NormalTok{(skadkost))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `summarise()` has grouped output by 'bonuskl', 'zon', 'mcklass', 'motorage_gr',
## 'kon'. You can override using the `.groups` argument.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Fit the Poisson GLM for frequency}
\NormalTok{model.freq.new }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(antskad }\SpecialCharTok{\textasciitilde{}}\NormalTok{ zon }\SpecialCharTok{+}\NormalTok{ mcklass }\SpecialCharTok{+}\NormalTok{ motorage\_gr }\SpecialCharTok{+}\NormalTok{ bonuskl }\SpecialCharTok{+}\NormalTok{ kon }\SpecialCharTok{*}\NormalTok{ driverage\_gr }\SpecialCharTok{+}\FunctionTok{offset}\NormalTok{(}\FunctionTok{log}\NormalTok{(duration)),}
                     \AttributeTok{family =}\NormalTok{ poisson, }
                     \AttributeTok{data =}\NormalTok{ grDataOhlsson.new[grDataOhlsson.new}\SpecialCharTok{$}\NormalTok{duration}\SpecialCharTok{\textgreater{}}\DecValTok{0}\NormalTok{,])}

\FunctionTok{with}\NormalTok{(model.freq.new, }
     \FunctionTok{cbind}\NormalTok{(}\AttributeTok{res.deviance =}\NormalTok{ deviance, }\AttributeTok{df =}\NormalTok{ df.residual, }
     \AttributeTok{p =} \FunctionTok{pchisq}\NormalTok{(deviance, df.residual, }\AttributeTok{lower.tail =} \ConstantTok{FALSE}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      res.deviance   df p
## [1,]     742.7633 1277 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{pchisq}\NormalTok{(model.freq.new}\SpecialCharTok{$}\NormalTok{deviance }\SpecialCharTok{{-}}\NormalTok{ model.freq}\SpecialCharTok{$}\NormalTok{deviance,}
\NormalTok{       model.freq.new}\SpecialCharTok{$}\NormalTok{df.residual }\SpecialCharTok{{-}}\NormalTok{ model.freq}\SpecialCharTok{$}\NormalTok{df.residual, }
       \AttributeTok{lower.tail=}\ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1
\end{verbatim}

We have combined the ages into 2 groups given by the breaks 0, 30, 100.
When including age and sex with an interaction term, for the frequency
the deviance goes to \(742.76\) on \(1277\) degrees of freedom. The LRT
statistic we get \(742.76 - 360.22 =382.55\) on \(1277 - 389=888\)
degrees of freedom. The corresponding p-value is \(1\), suggesting that
the simpler model is a better fit.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Fit the Gamma GLM for severity}
\NormalTok{model.sev.new }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(skadkost}\SpecialCharTok{/}\NormalTok{antskad }\SpecialCharTok{\textasciitilde{}}\NormalTok{ zon }\SpecialCharTok{+}\NormalTok{ mcklass }\SpecialCharTok{+}\NormalTok{ motorage\_gr }\SpecialCharTok{+}\NormalTok{ bonuskl }\SpecialCharTok{+}\NormalTok{ kon }\SpecialCharTok{*}\NormalTok{ driverage\_gr, }
                     \AttributeTok{family =} \FunctionTok{Gamma}\NormalTok{(}\StringTok{"log"}\NormalTok{), }
                     \AttributeTok{data =}\NormalTok{ grDataOhlsson.new[grDataOhlsson.new}\SpecialCharTok{$}\NormalTok{antskad}\SpecialCharTok{\textgreater{}}\DecValTok{0}\NormalTok{,],}
                     \AttributeTok{weights =}\NormalTok{ antskad)}

\FunctionTok{with}\NormalTok{(model.sev.new, }
     \FunctionTok{cbind}\NormalTok{(}\AttributeTok{res.deviance =}\NormalTok{ deviance, }\AttributeTok{df =}\NormalTok{ df.residual, }
     \AttributeTok{p =} \FunctionTok{pchisq}\NormalTok{(deviance, df.residual, }\AttributeTok{lower.tail =} \ConstantTok{FALSE}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      res.deviance  df            p
## [1,]     612.1475 288 1.706859e-25
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{pchisq}\NormalTok{(model.sev.new}\SpecialCharTok{$}\NormalTok{deviance }\SpecialCharTok{{-}}\NormalTok{ model.sev}\SpecialCharTok{$}\NormalTok{deviance }\SpecialCharTok{*} \FunctionTok{summary}\NormalTok{(model.sev)}\SpecialCharTok{$}\NormalTok{dispersion }\SpecialCharTok{/} \FunctionTok{summary}\NormalTok{(model.sev.new)}\SpecialCharTok{$}\NormalTok{dispersion, }
\NormalTok{       model.sev.new}\SpecialCharTok{$}\NormalTok{df.residual }\SpecialCharTok{{-}}\NormalTok{ model.sev}\SpecialCharTok{$}\NormalTok{df.residual,}
       \AttributeTok{lower.tail=}\ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 7.085095e-11
\end{verbatim}

For the severity however, the LRT statistic is given by \(253.12\) on
\(124\) degrees of freedom, with corresponding p-value given by
\(7.09 \times 10^{−11}\). Hence in this case, the age and sex do appear
to provide a model that has a better fit. We also see that for both the
frequency and the severity models, while sex is not a significant
factor, the interaction term between age and sex and the coefficient for
the age group 0-30 are both significant.

\hypertarget{question-6}{%
\subsection{Question 6}\label{question-6}}

Now combine your multiplier estimates for the frequency and severity
data to get multipliers (and associated 95\% confidence intervals) for
the premium overall and then propose a new tariff based on your
analysis. Compare the results to the old tariff.

\hypertarget{solution-5}{%
\paragraph{Solution:}\label{solution-5}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Generate the table for new tariff}
\NormalTok{table.q6 }\OtherTok{=} \FunctionTok{matrix}\NormalTok{(}\DecValTok{0}\NormalTok{, }\AttributeTok{nrow =} \FunctionTok{dim}\NormalTok{(motorcycle)[}\DecValTok{1}\NormalTok{] }\SpecialCharTok{+} \DecValTok{1}\NormalTok{, }\AttributeTok{ncol =} \DecValTok{5}\NormalTok{)}
\FunctionTok{colnames}\NormalTok{(table.q6) }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"Rating factor"}\NormalTok{, }\StringTok{"Class"}\NormalTok{, }\StringTok{"Multiplier"}\NormalTok{, }\StringTok{"Lower bound"}\NormalTok{, }\StringTok{"Upper bound"}\NormalTok{)}

\CommentTok{\# Intercept}
\NormalTok{estimate.freq }\OtherTok{=}\NormalTok{ mat.freq[}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{]}
\NormalTok{std.error.freq }\OtherTok{=}\NormalTok{ mat.freq[}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{]}
\NormalTok{estimate.sev }\OtherTok{=}\NormalTok{ mat.sev[}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{]}
\NormalTok{std.error.sev }\OtherTok{=}\NormalTok{ mat.sev[}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{]}
\NormalTok{table.q6[}\DecValTok{1}\NormalTok{, ] }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"Intercept"}\NormalTok{, }\StringTok{"0"}\NormalTok{, }\FunctionTok{exp}\NormalTok{(estimate.freq }\SpecialCharTok{+}\NormalTok{ estimate.sev), }
                  \FunctionTok{exp}\NormalTok{(estimate.freq }\SpecialCharTok{+}\NormalTok{ estimate.sev }\SpecialCharTok{{-}} \FloatTok{1.96} \SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(std.error.freq}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+}\NormalTok{ std.error.sev}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)), }
                  \FunctionTok{exp}\NormalTok{(estimate.freq }\SpecialCharTok{+}\NormalTok{ estimate.sev }\SpecialCharTok{+} \FloatTok{1.96} \SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(std.error.freq}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+}\NormalTok{ std.error.sev}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)))}

\CommentTok{\# Zone}
\NormalTok{estimate.freq }\OtherTok{=}\NormalTok{ P.zon }\SpecialCharTok{\%*\%}\NormalTok{ mat.freq[}\DecValTok{2}\SpecialCharTok{:}\DecValTok{7}\NormalTok{, }\DecValTok{1}\NormalTok{]}
\NormalTok{std.error.freq }\OtherTok{=}\NormalTok{ P.zon }\SpecialCharTok{\%*\%}\NormalTok{ mat.freq[}\DecValTok{2}\SpecialCharTok{:}\DecValTok{7}\NormalTok{, }\DecValTok{2}\NormalTok{]}
\NormalTok{estimate.sev }\OtherTok{=}\NormalTok{ P.zon }\SpecialCharTok{\%*\%}\NormalTok{ mat.sev[}\DecValTok{2}\SpecialCharTok{:}\DecValTok{7}\NormalTok{, }\DecValTok{1}\NormalTok{]}
\NormalTok{std.error.sev }\OtherTok{=}\NormalTok{ P.zon }\SpecialCharTok{\%*\%}\NormalTok{ mat.sev[}\DecValTok{2}\SpecialCharTok{:}\DecValTok{7}\NormalTok{, }\DecValTok{2}\NormalTok{]}
\NormalTok{table.q6[}\DecValTok{2}\SpecialCharTok{:}\DecValTok{8}\NormalTok{, ] }\OtherTok{=} \FunctionTok{cbind}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\StringTok{"Zone"}\NormalTok{, }\DecValTok{7}\NormalTok{), }\FunctionTok{seq}\NormalTok{(}\DecValTok{7}\NormalTok{), }\FunctionTok{exp}\NormalTok{(estimate.freq }\SpecialCharTok{+}\NormalTok{ estimate.sev), }
                  \FunctionTok{exp}\NormalTok{(estimate.freq }\SpecialCharTok{+}\NormalTok{ estimate.sev }\SpecialCharTok{{-}} \FloatTok{1.96} \SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(std.error.freq}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+}\NormalTok{ std.error.sev}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)), }
                  \FunctionTok{exp}\NormalTok{(estimate.freq }\SpecialCharTok{+}\NormalTok{ estimate.sev }\SpecialCharTok{+} \FloatTok{1.96} \SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(std.error.freq}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+}\NormalTok{ std.error.sev}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)))}

\CommentTok{\# Vehicle class}
\NormalTok{estimate.freq }\OtherTok{=}\NormalTok{ P.mcklass }\SpecialCharTok{\%*\%}\NormalTok{ mat.freq[}\DecValTok{8}\SpecialCharTok{:}\DecValTok{13}\NormalTok{, }\DecValTok{1}\NormalTok{]}
\NormalTok{std.error.freq }\OtherTok{=}\NormalTok{ P.mcklass }\SpecialCharTok{\%*\%}\NormalTok{ mat.freq[}\DecValTok{8}\SpecialCharTok{:}\DecValTok{13}\NormalTok{, }\DecValTok{2}\NormalTok{]}
\NormalTok{estimate.sev }\OtherTok{=}\NormalTok{ P.mcklass }\SpecialCharTok{\%*\%}\NormalTok{ mat.sev[}\DecValTok{8}\SpecialCharTok{:}\DecValTok{13}\NormalTok{, }\DecValTok{1}\NormalTok{]}
\NormalTok{std.error.sev }\OtherTok{=}\NormalTok{ P.mcklass }\SpecialCharTok{\%*\%}\NormalTok{ mat.sev[}\DecValTok{8}\SpecialCharTok{:}\DecValTok{13}\NormalTok{, }\DecValTok{2}\NormalTok{]}
\NormalTok{table.q6[}\DecValTok{9}\SpecialCharTok{:}\DecValTok{15}\NormalTok{, ] }\OtherTok{=} \FunctionTok{cbind}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\StringTok{"Vehicle class"}\NormalTok{, }\DecValTok{7}\NormalTok{), }\FunctionTok{seq}\NormalTok{(}\DecValTok{7}\NormalTok{), }\FunctionTok{exp}\NormalTok{(estimate.freq }\SpecialCharTok{+}\NormalTok{ estimate.sev), }
                   \FunctionTok{exp}\NormalTok{(estimate.freq }\SpecialCharTok{+}\NormalTok{ estimate.sev }\SpecialCharTok{{-}} \FloatTok{1.96} \SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(std.error.freq}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+}\NormalTok{ std.error.sev}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)), }
                   \FunctionTok{exp}\NormalTok{(estimate.freq }\SpecialCharTok{+}\NormalTok{ estimate.sev }\SpecialCharTok{+} \FloatTok{1.96} \SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(std.error.freq}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+}\NormalTok{ std.error.sev}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)))}
\CommentTok{\# Vehicle age}
\NormalTok{estimate.freq }\OtherTok{=}\NormalTok{ P.motorage\_gr }\SpecialCharTok{\%*\%}\NormalTok{ mat.freq[}\DecValTok{14}\SpecialCharTok{:}\DecValTok{15}\NormalTok{, }\DecValTok{1}\NormalTok{]}
\NormalTok{std.error.freq }\OtherTok{=}\NormalTok{ P.motorage\_gr }\SpecialCharTok{\%*\%}\NormalTok{ mat.freq[}\DecValTok{14}\SpecialCharTok{:}\DecValTok{15}\NormalTok{, }\DecValTok{2}\NormalTok{]}
\NormalTok{estimate.sev }\OtherTok{=}\NormalTok{ P.motorage\_gr }\SpecialCharTok{\%*\%}\NormalTok{ mat.sev[}\DecValTok{14}\SpecialCharTok{:}\DecValTok{15}\NormalTok{, }\DecValTok{1}\NormalTok{]}
\NormalTok{std.error.sev }\OtherTok{=}\NormalTok{ P.motorage\_gr }\SpecialCharTok{\%*\%}\NormalTok{ mat.sev[}\DecValTok{14}\SpecialCharTok{:}\DecValTok{15}\NormalTok{, }\DecValTok{2}\NormalTok{]}
\NormalTok{table.q6[}\DecValTok{16}\SpecialCharTok{:}\DecValTok{18}\NormalTok{, ] }\OtherTok{=} \FunctionTok{cbind}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\StringTok{"Vehicle age"}\NormalTok{, }\DecValTok{3}\NormalTok{), }\FunctionTok{seq}\NormalTok{(}\DecValTok{3}\NormalTok{), }\FunctionTok{exp}\NormalTok{(estimate.freq }\SpecialCharTok{+}\NormalTok{ estimate.sev), }
                    \FunctionTok{exp}\NormalTok{(estimate.freq }\SpecialCharTok{+}\NormalTok{ estimate.sev }\SpecialCharTok{{-}} \FloatTok{1.96} \SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(std.error.freq}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+}\NormalTok{ std.error.sev}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)), }
                    \FunctionTok{exp}\NormalTok{(estimate.freq }\SpecialCharTok{+}\NormalTok{ estimate.sev }\SpecialCharTok{+} \FloatTok{1.96} \SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(std.error.freq}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+}\NormalTok{ std.error.sev}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)))}
\CommentTok{\# Bonus class}
\NormalTok{estimate.freq }\OtherTok{=}\NormalTok{ P.motorage\_gr }\SpecialCharTok{\%*\%}\NormalTok{ mat.freq[}\DecValTok{16}\SpecialCharTok{:}\DecValTok{17}\NormalTok{, }\DecValTok{1}\NormalTok{]}
\NormalTok{std.error.freq }\OtherTok{=}\NormalTok{ P.motorage\_gr }\SpecialCharTok{\%*\%}\NormalTok{ mat.freq[}\DecValTok{16}\SpecialCharTok{:}\DecValTok{17}\NormalTok{, }\DecValTok{2}\NormalTok{]}
\NormalTok{estimate.sev }\OtherTok{=}\NormalTok{ P.motorage\_gr }\SpecialCharTok{\%*\%}\NormalTok{ mat.sev[}\DecValTok{16}\SpecialCharTok{:}\DecValTok{17}\NormalTok{, }\DecValTok{1}\NormalTok{]}
\NormalTok{std.error.sev }\OtherTok{=}\NormalTok{ P.motorage\_gr }\SpecialCharTok{\%*\%}\NormalTok{ mat.sev[}\DecValTok{16}\SpecialCharTok{:}\DecValTok{17}\NormalTok{, }\DecValTok{2}\NormalTok{]}
\NormalTok{table.q6[}\DecValTok{19}\SpecialCharTok{:}\DecValTok{21}\NormalTok{, ] }\OtherTok{=} \FunctionTok{cbind}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\StringTok{"Bonus class"}\NormalTok{, }\DecValTok{3}\NormalTok{), }\FunctionTok{seq}\NormalTok{(}\DecValTok{3}\NormalTok{), }\FunctionTok{exp}\NormalTok{(estimate.freq }\SpecialCharTok{+}\NormalTok{ estimate.sev), }
                    \FunctionTok{exp}\NormalTok{(estimate.freq }\SpecialCharTok{+}\NormalTok{ estimate.sev }\SpecialCharTok{{-}} \FloatTok{1.96} \SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(std.error.freq}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+}\NormalTok{ std.error.sev}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)), }
                    \FunctionTok{exp}\NormalTok{(estimate.freq }\SpecialCharTok{+}\NormalTok{ estimate.sev }\SpecialCharTok{+} \FloatTok{1.96} \SpecialCharTok{*} \FunctionTok{sqrt}\NormalTok{(std.error.freq}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{+}\NormalTok{ std.error.sev}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)))}

\CommentTok{\# Append the old tariff}
\NormalTok{tariff.old }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }
                \FloatTok{7.768}\NormalTok{, }\FloatTok{4.227}\NormalTok{, }\FloatTok{1.336}\NormalTok{, }\FloatTok{1.000}\NormalTok{, }\FloatTok{1.734}\NormalTok{, }\FloatTok{1.402}\NormalTok{, }\FloatTok{1.402}\NormalTok{,}
                \FloatTok{0.625}\NormalTok{, }\FloatTok{0.769}\NormalTok{, }\FloatTok{1.000}\NormalTok{, }\FloatTok{1.406}\NormalTok{, }\FloatTok{1.875}\NormalTok{, }\FloatTok{4.062}\NormalTok{, }\FloatTok{6.873}\NormalTok{,}
                \FloatTok{2.000}\NormalTok{, }\FloatTok{1.200}\NormalTok{, }\FloatTok{1.000}\NormalTok{,}
                \FloatTok{1.250}\NormalTok{, }\FloatTok{1.125}\NormalTok{, }\FloatTok{1.000}\NormalTok{)}

\NormalTok{table.q6 }\OtherTok{\textless{}{-}} \FunctionTok{cbind}\NormalTok{(table.q6, tariff.old)}
\FunctionTok{as\_tibble}\NormalTok{(table.q6)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 21 x 6
##    `Rating factor` Class Multiplier       `Lower bound` `Upper bound` tariff.old
##    <chr>           <chr> <chr>            <chr>         <chr>         <chr>     
##  1 Intercept       0     36.8117381881973 24.648022842~ 54.978205638~ 0         
##  2 Zone            1     6.70508427358011 4.6837045832~ 9.5988451698~ 7.768     
##  3 Zone            2     3.73268334757043 2.6009695305~ 5.3568197588~ 4.227     
##  4 Zone            3     1.5998221736057  1.0777977596~ 2.3746857555~ 1.336     
##  5 Zone            4     1                1             1             1         
##  6 Zone            5     0.8735824081835~ 0.2693243878~ 2.8335578147~ 1.734     
##  7 Zone            6     0.81205107042752 0.3456349663~ 1.9078710351~ 1.402     
##  8 Zone            7     0.0128496625225~ 0.0004116919~ 0.4010616354~ 1.402     
##  9 Vehicle class   1     1.10256594294937 0.6206206667~ 1.9587676073~ 0.625     
## 10 Vehicle class   2     1.40354376694843 0.8237368936~ 2.3914615465~ 0.769     
## 11 Vehicle class   3     1                1             1             1         
## 12 Vehicle class   4     1.05389848011396 0.6789605646~ 1.6358858882~ 1.406     
## 13 Vehicle class   5     1.70368012750906 1.1452046573~ 2.5345041676~ 1.875     
## 14 Vehicle class   6     4.11778454895722 2.7862232716~ 6.0857109924~ 4.062     
## 15 Vehicle class   7     4.74582556460639 1.1200092081~ 20.109531356~ 6.873     
## 16 Vehicle age     1     8.280514791945   5.8053034789~ 11.811083687~ 2         
## 17 Vehicle age     2     4.44415271450964 3.1665581941~ 6.2372115523~ 1.2       
## 18 Vehicle age     3     1                1             1             1         
## 19 Bonus class     1     1.48749997458448 1.0355565557~ 2.1366830832~ 1.25      
## 20 Bonus class     2     1.06615050675576 0.7792268847~ 1.4587239292~ 1.125     
## 21 Bonus class     3     1                1             1             1
\end{verbatim}

We see that the new tariff is much higher than the old one for Vehicle
Age 1 and 2. We also see that for Zone 5 to 7, the new tariff suggests
to lower the premium compared to the baseline of Zone 4, while for the
old tariff they were all higher than the baseline. The number of claims
for these 3 zones is very small though, so it seems like it might be
best to not make such an important change based on such a small sample.

\hypertarget{question-7}{%
\subsection{Question 7}\label{question-7}}

Comment on any further analysis that should be considered before
deciding on a final tariff.

\hypertarget{solution-6}{%
\paragraph{Solution:}\label{solution-6}}

we saw that, especially for the severity, the age and sex seem to be
significant factors that should be considered. On the other hand,
looking at the results for coefficients in each of the frequency and
severity models (reproduced below), we see that Zones 5,6,7 (note that
although the results below are based on the ordering of levels by
decreasing order of duration, and therefore do not necessarily
correspond to the original numbering, for these 3 particular classes are
actually the same as in the original ordering) do not seem to be
significant, and should therefore probably be combined with the baseline
of Zone 4. Finally, we should explore the use of models other than the
gamma distribution for the severity, to see if a better fit can be
obtained. 5

\end{document}
